import os

_basedir = os.path.abspath(os.path.dirname(__file__))

DEBUG = False
SECRET_KEY = 'DONOTUSEINPRODUCTION'
INVITE_KEY = 'DONTUSEINPRODUCTION'
RESET_KEY = 'DONTUSEINPRODUCTION'
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/test.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
NOREPLY_EMAIL = os.environ['NOREPLY_EMAIL']
ADMIN_EMAIL = os.environ['ADMIN_EMAIL']
SENDGRID_APIKEY = os.environ['SENDGRID_APIKEY']

del os
